drop database IF EXISTS audioantTest;
create database audioantTest;
use audioantTest;

CREATE TABLE Tests (
	ID INTEGER PRIMARY KEY AUTO_INCREMENT,
	TestDate TIMESTAMP NOT NULL,
	FileType VARCHAR(5)
);

CREATE TABLE Sounds (
	ID INTEGER PRIMARY KEY AUTO_INCREMENT,
	Name VARCHAR(100) NOT NULL
);

CREATE TABLE Results (
	ID INTEGER PRIMARY KEY AUTO_INCREMENT,
	TestID INTEGER NOT NULL,
	SoundID INTEGER NOT NULL,
	FileName VARCHAR(100) NOT NULL,
	ShouldBeRecognised BOOLEAN NOT NULL,
	WasRecognised BOOLEAN NOT NULL,
	CorrectRecognition BOOLEAN NOT NULL
);

CREATE TABLE FeatureMatch (
	ID INTEGER PRIMARY KEY AUTO_INCREMENT,
	ResultID INTEGER NOT NULL,
	StrongestFrequency DOUBLE
);